version: '3.8'

services:
  frontend:
    build: ./review
    ports:
      - "80:80"  # Теперь используем стандартный HTTP-порт
    networks:
      - frontend-network

  backend:
    build: ./sentiment_analysis
    ports:
      - "5233:5233"
    volumes:
      - ./db.db:/app/db.db
      - ./sentiment_analysis:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_PATH=/app/db.db
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge